<?php
/**
 * Created by PhpStorm.
 * User: malek
 * Date: 4/26/2018
 * Time: 12:42 AM
 */

namespace BonPlanBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{

    public function findequi($p)
    {

        $query=$this->getEntityManager()->createQuery(
            "select p from BonPlanBundle:Commentraire c JOIN BonPlanBundle:User p WITH c.idUcomm=p WHERE c.idCommentaire=:l "
        )->setParameter('l',$p);
        return $query->getResult();

    }

}