<?php
/**
 * Created by PhpStorm.
 * User: malek
 * Date: 4/26/2018
 * Time: 12:42 AM
 */

namespace BonPlanBundle\Repository;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class FavorisRepository extends \Doctrine\ORM\EntityRepository
{

    public function findequi($p)
    {

        $query=$this->getEntityManager()->createQuery(
            "select p from BonPlanBundle:Favoris c JOIN BonPlanBundle:Etablissement p WITH c.idEtablissement=p WHERE c.id=:l "
        )->setParameter('l',$p);
        return $query->getResult();

    }

}