<?php

namespace BonPlanBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findequi($p)
    {

        $query=$this->getEntityManager()->createQuery(
            "select c from BonPlanBundle:Reservation c JOIN BonPlanBundle:Etablissement p WITH c.idEtablissement=p  WHERE  p.id = :l and c.checked = FALSE "
        )->setParameter('l',$p);
        return $query->getResult();

    }

    public function cal($p)
    {

        $query=$this->getEntityManager()->createQuery(
            "select c from BonPlanBundle:Reservation c JOIN BonPlanBundle:Etablissement p WITH c.idEtablissement=p  WHERE  p.id = :l and c.checked = TRUE and c.valid = TRUE "
        )->setParameter('l',$p);
        return $query->getResult();

    }

}