<?php
/**
 * Created by PhpStorm.
 * User: Nadia
 * Date: 06/04/2018
 * Time: 14:33
 */

namespace BonPlanBundle\EtablissementBundle\Repository;
use BonPlanBundle\Entity\Etablissement;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class EtablissementRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindByLetters($string)
{
    $query = $this->getEntityManager()->createQuery("SELECT e FROM BonPlanBundle:Etablissement e WHERE e.nomEtablissement like :tit")
        ->setParameter('tit','%'.$string.'%');
    return $query->getResult();
}
    public function CountNbFavoris($id)
    {
        $query = $this->getEntityManager()->createQuery("select count (f.idFavoris) as nb from BonPlanBundle:Favoris f  WHERE  f.idEtablissement=:n  ")
            ->setParameter('n',$id);
        return $query->getSingleScalarResult();
    }
    public function CalculRating($id)
    {
        $query = $this->getEntityManager()->createQuery("select AVG(ev.note) from BonPlanBundle:Evaluation ev, BonPlanBundle:Etablissement et, BonPlanBundle:Experience ex, BonPlanBundle:CritereEvaluation cv where et.idEtablissement = ex.idEtablissement and ev.idExp=ex.idExp and cv.idCritere=ev.idCritere and et.idEtablissement=:n GROUP BY ev.idCritere  ")
            ->setParameter('n',$id);
        return $query->getResult();
    }
    public function CountNbEtabParCategorie($id)
    {
        $query = $this->getEntityManager()->createQuery("select count (e.idEtablissement) as nb from BonPlanBundle:Etablissement e WHERE e.enabled=1 AND e.idCategorie=:n  ")
            ->setParameter('n',$id);
        return $query->getSingleScalarResult();
    }

}